### ISSUE TITLE
Acceptance tests: Allow configurable timeout in read tests

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-connector-sdk#23]
### Feature description

An acceptance test utilizing reads will fail if a record cannot be read in 5 seconds ([link](https://github.com/ConduitIO/conduit-connector-sdk/blob/733149cddc0bcdfd1144012f1bf41651355653d1/acceptance_testing.go#L942)).

For some sources that's still too much, especially in certain snapshots. Concretely, we have this problem with the Marketo source.

**Comment by rustiever** [comment]
Can we replace wherever we use ctx timeout with `a.driver.ReadTimeout()` For eg: https://github.com/ConduitIO/conduit-connector-sdk/blob/511c321558fce7912208632e94c60518aecc5d11/acceptance_testing.go#L707. Because some connectors like marketo takes some time to pull the data, which is some time, limitation of third party system. [here](https://github.com/ConduitIO/conduit-connector-sdk/blob/511c321558fce7912208632e94c60518aecc5d11/acceptance_testing.go#L1050) as well

**Comment by neovintage** [comment]
@lovromazgon did you fix this?

**Comment by lovromazgon** [comment]
Hopefully 🙂 See https://github.com/ConduitIO/conduit-connector-sdk/pull/29.
