### ISSUE TITLE
Bug: Some acceptance tests `Teardown` without `Open`

### ISSUE THREAD

**Issue by nassor** [ConduitIO/conduit-connector-sdk#78]
### Bug description

The acceptance tests:

- `TestDestination_Configure_RequiredParams`
- `TestDestination_Configure_Success`
- `TestSource_Configure_RequiredParams`
- `TestSource_Configure_Success`

Are calling the `Teardown` method without previously calling the `Open` method. I am assuming that the [documentation is correct](https://github.com/ConduitIO/conduit-connector-sdk/blob/40bec2e6530c54b226afdf87e6d3ab7b384ebf2e/destination.go#L52).

`Teardown` will crash because the resources that should be initialized by `Open` are not in place (`nil`).

### Steps to reproduce

1. In this branch: https://github.com/conduitio-labs/conduit-connector-nats-jetstream/tree/fix/destination-reconnection
2. Remove the skip tests from `acceptance_test.go`
3. See the acceptance tests panicking because `nil` pointers (because `Open` wasn't called)

### Version

v0.6.0

**Comment by lovromazgon** [comment]
These tests work as intended, `Teardown` can in fact be called without previously calling `Open`. When the connector is first created, Conduit calls `Configure` and then `Teardown` to signal that the connector process will stop running. The purpose is to give the connector a chance to validate the configuration, since we don't want to create a connector with an invalid configuration. We call `Teardown` at the end, as we want to guarantee that it is always the last method that's called before the connector stops, regardless of what was called before, in case there is any cleanup that needs to happen.

**Comment by nassor** [comment]
So, that means that I need to use Configure to initialize the resources?

**Comment by lovromazgon** [comment]
> So, that means that I need to use Configure to initialize the resources?

Not really, all that means is that `Teardown` is [hardwired](https://github.com/ConduitIO/conduit/blob/9d2aab73633a816fce9f048e8ff4835a99d99e09/pkg/plugin/standalone/v1/dispenser.go#L179-L180C37) to be the last method called before the connector stops running. You can see it as a signal that the process will stop and it's the last chance to do _anything_. What happens before that call depends on the context:
- If the connector is being created, Conduit will call `Configure` to validate the configuration and then `Teardown`.
- If the connector is being started as part of a starting pipeline, Conduit will call all methods provided by the connector as explained in the docs. That's the "happy path". If any of those functions return an error, the lifecycle can be ended early (i.e. if `Configure` returns an error, it goes straight to `Teardown`).
- If the connector is being deleted, Conduit will call `LifecycleOnDeleted` to give the connector a chance to delete any long-living resources (e.g. replication slot) and then `Teardown`.
